name: Recon

on:
  push:
    branches: [master]

jobs:
  scan-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          set -e
          sudo apt-get update && sudo apt-get install -y wget unzip jq golang
          go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest && sudo mv ~/go/bin/httpx /usr/bin/
          go install github.com/cybercdh/assetfinder@cybercdh && sudo mv ~/go/bin/assetfinder /usr/bin/
          go install github.com/tomnomnom/httprobe@latest && sudo mv ~/go/bin/httprobe /usr/bin/
          LATEST_VERSION=$(curl -s https://api.github.com/repos/projectdiscovery/nuclei/releases/latest | jq -r '.tag_name')
          CLEAN_VERSION=${LATEST_VERSION#v}
          wget https://github.com/projectdiscovery/nuclei/releases/download/${LATEST_VERSION}/nuclei_${CLEAN_VERSION}_linux_amd64.zip
          unzip -o nuclei_${CLEAN_VERSION}_linux_amd64.zip
          sudo mv nuclei /usr/bin/
          sudo rm -rf nuclei* *.md

      - name: Get all domains and reconnaissance
        run: |
          curl -s "https://www.shop-apotheke.com" \
          | assetfinder -subs-only | nuclei -silent -severity medium,high,critical,unknown -o shop-apotheke.com.$(date +%Y-%m-%d_%H-%M-%S).txt

      - name: Set up Git user
        run: |
          git config --global user.email "${{ secrets.EMAIL_ADDRESS }}"
          git config --global user.name "${{ secrets.USER_NAME }}"

      - name: Pull remote changes
        run: git pull origin master --rebase || true

      - name: Commit changes
        run: |
          git add .
          git commit -m "Result scan $(date -u)" --no-verify || echo "No changes to commit"

      - name: Push changes
        uses: actions/checkout@v3
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
