name: Recon

on:
  push:
    branches: [master]

jobs:
  cve-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y wget unzip jq golang
          go install github.com/cybercdh/assetfinder@cybercdh && sudo mv ~/go/bin/assetfinder /usr/bin/
          go install github.com/tomnomnom/httprobe@latest && sudo mv ~/go/bin/httprobe /usr/bin/
          
      - name: Install or Update Nuclei
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/projectdiscovery/nuclei/releases/latest | jq -r '.tag_name')
          CLEAN_VERSION=${LATEST_VERSION#v}
          wget https://github.com/projectdiscovery/nuclei/releases/download/${LATEST_VERSION}/nuclei_${CLEAN_VERSION}_linux_amd64.zip
          unzip -o nuclei_${CLEAN_VERSION}_linux_amd64.zip
          sudo mv nuclei /usr/bin/
          sudo rm -rf nuclei* *.md

      - name: Scan for CVEs
        run: |
          # Input domains and run nuclei with CVE templates
          curl -s "https://gist.githubusercontent.com/z0rs/5c99a59edb510be0302a76c86800233d/raw/a5c210cdc6be23ec2e92ba2475588d34c3f4cf3e/yacht.nl" \
          | httprobe -c 50 -t 3000 \
          | sed 's/https\?:\/\///g; s/www\.//g; s/http\?:\/\///g' \
          | nuclei -silent -t cves/ -rl 3 -bs 3 -timeout 20 -retries 2 \
          | tee cve-scan.$(date +%Y-%m-%d).txt
          
      - name: Set up Git user
        run: |
          git config --global user.email "${{ secrets.EMAIL_ADDRESS }}"
          git config --global user.name "${{ secrets.USER_NAME }}"
          
      - name: Commit and push CVE scan results
        run: |
          git add cve-scan.$(date +%Y-%m-%d).txt
          git commit -m "CVE scan result $(date -u)" --no-verify
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
